### ISSUE TITLE
add rama metrics to fly.io deployments

### ISSUE THREAD

**Issue by GlenDC** [plabayo/rama#175]
- rama-fp
- rama-echo

Doc link: https://fly.io/docs/metrics-and-logs/metrics/#prometheus-on-fly-io

To tomls:

```toml
[metrics]
port = 9091
path = "/metrics"
```
